### ISSUE TITLE
Avoid generating property accessors for properties originating from an interface

### ISSUE THREAD

**Issue by alatiera** [gtk-rs/gir#1369] opened 2022-06-20 20:27 UTC
For example, we generate wrappers for `item-type` which go through the properties, but its much better to cast the object and go through the `gio::ListModel` api instead.

_Originally posted by @ebassi in https://github.com/gtk-rs/gtk4-rs/pull/1056#discussion_r899447699_

**Comment by sdroege** [comment] 2022-07-09 11:14
@bilelmoussaoui Any updates on this? I remember you wanted to look into it some time ago

**Comment by bilelmoussaoui** [comment] 2022-07-16 15:23
I just did a quick look at fixing this, there were cases when we did generate a getter/notify signal that were duplicate of the parent interface/class but that is not the case for those new types that implements GListModel, as the GListModel interface doesn't require such properties at all. So there is actually not much to fix from our side here other than manually configuring those types to not generate a getter for those new properties.

**Closed** 2022-07-18 08:23 UTC
